### ISSUE TITLE
TAO Dashboard Update is not working

### ISSUE THREAD

**Issue by Saurabh-QS** [aws-samples/aws-cudos-framework-deployment#467] opened 2023-01-18 12:08 UTC
Thanking for fixing and enhancing so many things with this upgrade. I am really happy especially for the cost optimization tab bug fixing however I need your on the following.
I am getting the following issues while upgrading the TAO dashboards. I have reached out to you on LinkedIn as well 😊
C:\Users\xxx\OneDrive - BT Plc\Documents\dcpcli_1.0.4_Windows_x86_64>cid-cmd update --dashboard-id ta-organizational-view
CLOUD INTELLIGENCE DASHBOARDS (CID) CLI 0.2.11 Beta

Loading plugins...
        Core loaded

Checking AWS environment...
        profile name: default
        accountId: 058646147213
        AWS userId: Dcp-QuickSight-Role-eu-west-2/614938331
        Region: eu-west-2

Discovering deployed dashboards...  [####################################]  100%  "Trusted Advisor Organizational View" (ta-organiza

Latest template: arn:aws:quicksight:us-east-1:223485597511:template/ta-organizational-view/version/14
An update is available:
                   Deployed -> Latest
  CID Version      N/A         v2.0.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Scripts\cid-cmd.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\cli.py", line 28, in wrapper
    res = func(ctx, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\cli.py", line 162, in update
    ctx.obj.update(dashboard_id, force=force, recursive=recursive, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 164, in wrap
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 773, in update
    return self._deploy(dashboard_id, recursive=recursive, update=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 319, in _deploy
    compatible = self.check_dashboard_version_compatibility(dashboard_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 811, in check_dashboard_version_compatibility
    print(f"  TemplateVersion  {str(dashboard.deployedTemplate.version): <9}   {dashboard.latest_version: <6}")
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'version'
 

Also, when I try to run it for any other TAO which I have created from the main TAO dashboard by passing through the dashboard id in the command. It throws the following error. This is the one with row-level security enabled. 

File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 296, in _deploy raise ValueError(f'Cannot find dashboard with id={dashboard_id} in resources file.') ValueError: Cannot find dashboard with id=5dcae1fa-62f6-4e9f-a42b-fe250244fa34 in resources file.

After running the following command. I am getting the same sort of error.

Discovering deployed dashboards...  [####################################]  100%  "Trusted Advisor Organizational View" (ta-organiza

? [dashboard-id] Please select installation(s) from the list: Trusted Advisor Organizational View (arn:aws:quicksight:eu-west-2:058646147213:dashboard/ta-organizational-view, healthy, update available
-1->14)

Latest template: arn:aws:quicksight:us-east-1:223485597511:template/ta-organizational-view/version/14
An update is available:
                   Deployed -> Latest
  CID Version      N/A         v2.0.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Scripts\cid-cmd.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\cli.py", line 28, in wrapper
    res = func(ctx, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\cli.py", line 162, in update
    ctx.obj.update(dashboard_id, force=force, recursive=recursive, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 164, in wrap
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 773, in update
    return self._deploy(dashboard_id, recursive=recursive, update=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 319, in _deploy
    compatible = self.check_dashboard_version_compatibility(dashboard_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 811, in check_dashboard_version_compatibility
    print(f"  TemplateVersion  {str(dashboard.deployedTemplate.version): <9}   {dashboard.latest_version: <6}")
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'version'

C:\Users\xxx\OneDrive - BT Plc\Documents\dcpcli_1.0.4_Windows_x86_64>

**Comment by yprikhodko** [comment] 2023-01-18 14:38
The issue happens because the dashboards which were deployed/updated while ago don't have a template version in the arn. We've updated cid-cmd to handle this. Could you please update it and run tao update again with recursive flag 
```
python3 -m ensurepip --upgrade
pip3 install --upgrade cid-cmd
cid-cmd update --dashboard-id ta-organizational-view --recursive
```

**Comment by Saurabh-QS** [comment] 2023-01-23 10:59
Updating dataset: "ta-organizational-view"
Detected views:
Missing views: ta_org_view

? [view-ta-organizational-view-reports-s3FolderPath] Required parameter: s3FolderPath (Trusted Advisor Organization View report S3 path): s3://finops-058646xxxx3-c
ostoptimizationdata0586461xxxx/optics-data-collector/ta-data/
Updating table ta_organizational_view_reports
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Scripts\cid-cmd.exe\__main__.py", line 7, in <module>
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\cli.py", line 28, in wrapper
    res = func(ctx, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\cli.py", line 162, in update
    ctx.obj.update(dashboard_id, force=force, recursive=recursive, **kwargs)
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 164, in wrap
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 773, in update
    return self._deploy(dashboard_id, recursive=recursive, update=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 332, in _deploy
    self.create_datasets(required_datasets, dashboard_datasets, recursive=recursive, update=update)
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 922, in create_datasets
    if self.create_or_update_dataset(dataset_definition, dataset_id, recursive=recursive, update=update):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 1147, in create_or_update_dataset
    self.create_or_update_view(view_name, recursive=recursive, update=update)
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 1208, in create_or_update_view
    self.create_or_update_view(dep_view_name, recursive=recursive, update=update)
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\common.py", line 1217, in create_or_update_view
    self.glue.create_or_update_table(view_name, view_query)
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\site-packages\cid\helpers\glue.py", line 18, in create_or_update_table
    table = json.loads(view_query)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yyy\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 6 column 52 (char 195)

**Comment by yprikhodko** [comment] 2023-01-23 14:26
The issue is related to provided s3 folder path. Could you please make sure that you've pasted S3 folder path as one like and it doesn't have any special characters like quotes?

**Comment by pkujala** [comment] 2023-01-23 16:30
Thanks @yprikhodko, removing dataset from Quicksight helped and cid-cfn.yml stack updated without errors with parameter DeployTAODashboard set to yes. Dashboard shows data also.

**Comment by Saurabh-QS** [comment] 2023-01-26 11:47
Yes, I am prpviding the correct S3 path but it's not working. This is how I am providing S3 Path:  "s3://finops-058646147213-costoptimizationdata058646147213/optics-data-collector/ta-data/"

**Comment by yprikhodko** [comment] 2023-07-06 13:56
Closing. If it's still an issue please comment here

**Closed by yprikhodko** 2023-07-06 13:56 UTC
